<?php
/*
    Plugin Name: WP Themifier Runtime
    Plugin URI:  http://github.com/xemlock/wp-themifier-runtime
    Description: Runtime library for themes generated by WP Themifier.
    Version:     1.0-dev
    Author:      xemlock
    Author URI:  http://xemlock.pl/
    License:     GPL v2.0
    License URI: http://www.gnu.org/licenses/gpl-2.0.html
*/

/**
 * Get current language or language property.
 *
 * If Polylang plugin is active, its current language is returned, otherwise
 * a default language (English) is returned.
 *
 * @param  string $property OPTIONAL
 * @return object|string
 */
function themifier_get_language($property = null) // {{{
{
    static $fallback_language;
    global $polylang;

    if ($polylang) {
        $language = $polylang->curlang;
    }

    if (empty($language)) {
        if (empty($fallback_language)) {
            // wp-admin path is hardcoded in wp-includes/l10n.php so we don't
            // really if it's the proper way of including files from admin dir
            require_once ABSPATH . 'wp-admin/includes/translation-install.php';
            $translations = wp_get_available_translations();

            $locale = get_locale();
            $code = themifier_lang_code($locale);

            // try to obtain language data, first check using locale, then
            // using language code derived from locale. If that fails fall
            // back to English (en_US)
            if (isset($translation[$locale])) {
                $data = $translations[$locale];

            } elseif (isset($translations[$code])) {
                $data = $translations[$code];

            } else {
                $data = array(
                    'language'    => 'en_US',
                    'native_name' => 'English',
                );
            }

            $fallback_language = (object) array(
                'name'       => $data['native_name'],
                'locale'     => $data['language'],
                'slug'       => themifier_lang_code($data['language']),
                'home_url'   => home_url(),
                'search_url' => home_url(),
            );
        }
        $language = $fallback_language;
    }

    if (null === $property) {
        return $language;
    }

    return $language->{$property};
} // }}}

/**
 * Get available languages.
 *
 * Returned array of languages is non-empty. If no language is specified
 * default language (English) will be used.
 *
 * @return array
 */
function themifier_get_languages() // {{{
{
    global $polylang;

    if ($polylang) {
        $languages = $polylang->model->get_languages_list();
        return $languages;
    }

    return array(themifier_get_language());
} // }}}

/**
 * Get two letter language code of a given or, if no language provided,
 * current language.
 *
 * If no language code can be determined, a default value 'en' will be
 * returned.
 *
 * @param object|string $lang
 * @return string
 */
function themifier_lang_code($lang = null) // {{{
{
    if (null === $lang) {
        $lang = themifier_get_language();
    }

    if (is_object($lang)) {
        $locale = $lang->locale;
    } else {
        $locale = (string) $lang;
    }

    return substr($locale, 0, 2);
} // }}}

/**
 * Inserts language code as a GET param in the given URL.
 *
 * @param  string $url
 * @param  string $slug
 * @return string
 */
function themifier_url_insert_lang($url, $slug) // {{{
{
    // make sure no URL parts interferes with sprintf format
    $url = str_replace(array('%s', '%S'), array('%25s', '%25S'), $url);
    $url = preg_replace('/([?&])lang=[a-z]+/i', '\1lang=%s', $url, -1, $count);
    if (0 === $count) {
        $url .= false === strpos($url, '?')
            ? '?lang=%s'
            : '&lang=%s';
    }
    return sprintf($url, $slug);
} // }}}

/**
 * Get home URL for a given language.
 *
 * @param  string $slug OPTIONAL
 * @return string
 */
function themifier_home_url($slug = null) // {{{
{
    if (function_exists('pll_home_url')) {
        return pll_home_url($slug);
    }

    $url = get_home_url();

    if (null !== $slug) {
        $url = themifier_url_insert_lang($url, $slug);
    }

    return $url;
} // }}}

/**
 * Get post language.
 *
 * @param  int $post_id OPTIONAL
 * @return object|null
 */
function themifier_get_post_language($post_id = null) // {{{
{
    global $polylang;

    if ($polylang) {
        // well... this should be a public feature of Polylang
        $language = $polylang->model->get_post_language($post_id);
    }

    return empty($language) ? null : $language;
} // }}}

/**
 * Get term language.
 *
 * @param  int $term_id OPTIONAL
 * @return object|null
 */
function themifier_get_term_language($term_id = null) // {{{
{
    global $polylang;

    if ($polylang) {
        // well... this should be a public feature of Polylang
        $language = $polylang->model->get_term_language($term_id);
    }

    return empty($language) ? null : $language;
} // }}}

/**
 * Get transation URL for the given language of the current site.
 *
 * @param  $slug OPTIONAL
 * @return string
 */
function themifier_get_translation_url($slug = null) // {{{
{
    global $post, $polylang;

    if (null === $slug) {
        $slug = themifier_get_language('slug');
    }

    switch (true) {
        case is_single():
        case is_page():
            $translation_id = themifier_get_translation_id('post', $post->ID, $slug);
            if ($translation_id) {
                $url = get_permalink($translation_id);
            }
            break;

        case is_category():
        case is_tag():
            // cannot use get_the_category() as it does not return current
            // category, but a list of categories _current_ post is attached to
            $category = get_queried_object();

            $translation_id = themifier_get_translation_id('term', $category->term_id, $slug);
            if ($translation_id) {
                if (is_category()) {
                    $url = get_category_link($translation_id);
                } elseif (is_tag()) {
                    $url = get_tag_link($translation_id);
                }
            }
            break;

        case is_object($polylang):
            $url = $polylang->links->get_translation_url($slug);
            break;
    }

    if (empty($url)) {
        // no translation found, redirect to home page in the given
        // language. Do not try to append lang url param to current
        // url, as it would result in an infinite redirection loop
        // caused by themifier_check_language()
        $url = themifier_home_url($slug);
    }

    return $url;
} // }}}

/**
 * Get translation ID of a given post or term using a Polylang module
 * (if available).
 *
 * @param  string $type
 * @param  int $id
 * @param  string $slug OPTIONAL
 * @return string|null
 */
function themifier_get_translation_id($type, $id, $slug = null) // {{{
{
    if (null === $slug) {
        $slug = themifier_get_language('slug');
    }

    switch ($type) {
        case 'post':
            if (function_exists('pll_get_post')) {
                return pll_get_post($id, $slug);
            }
            break;

        case 'term':
            if (function_exists('pll_get_term')) {
                return pll_get_term($id, $slug);
            }
            break;

        default:
            break;
    }
} // }}}

/**
 * Hook checking if the language of the current post or category matches
 * the language in the current viewing context.
 *
 * @return void
 */
function themifier_check_language() // {{{
{
    global $post;

    $lang_mismatch = false;

    if (is_category()) {
        $category = get_queried_object();
        $lang = themifier_get_term_language($category->term_id);
        if ($lang && $lang->slug != themifier_get_language('slug')) {
            $lang_mismatch = true;
        }
    }

    if (is_single()) {
        $lang = themifier_get_post_language($post->ID);
        if ($lang && $lang->slug != themifier_get_language('slug')) {
            $lang_mismatch = true;
        }
    }

    if ($lang_mismatch) {
        if (isset($_SESSION)) {
            session_write_close();
        }
        header('Location: ' .  themifier_get_translation_url());
        exit;
    }
} // }}}

/**
 * Filter that sets up a default redirection URL after successful logout.
 *
 * @param  string $logout_url
 * @param  string $redirect OPTIONAL
 * @return string
 */
function themifier_logout_url($logout_url, $redirect = '') // {{{
{
    if (empty($redirect)) {
        $redirect = urlencode(themifier_home_url());
    }
    if (strpos($logout_url, '?') === false) {
        $logout_url .= '?redirect_to=' . $redirect;
    } else {
        $logout_url .= '&redirect_to=' . $redirect;
    }

    return $logout_url;
} // }}}

/**
 * Render navigation menu.
 *
 * @param  array|string $options OPTIONAL
 * @return string|void
 */
function themifier_nav_menu($options = null) // {{{
{
    $defaults = array(
        'container'   => 'nav',
        'depth'       => 2,
        'walker'      => null,
        'fallback_cb' => null,
        'items_wrap'  => '<ul id="{id}" class="{class}">{items}</ul>',
        'echo'        => false,
    );
    $options = wp_parse_args($options, $defaults);

    $options['theme_location'] = (string) $theme_location;
    $options['items_wrap'] = strtr($options['items_wrap'], array(
        '{id}'    => '%1$s', // options[menu_id]
        '{class}' => '%2$s', // options[menu_class]
        '{items}' => '%3$s',
    ));

    if (empty($options['walker'])) {
        require_once dirname(__FILE__) . '/bootstrap-navwalker.php';

        $options['walker'] = new themifier_bootstrap_navwalker();
        $options['fallback_cb'] = 'wp_bootstrap_navwalker::fallback';
    }

    // wp-includes/nav-menu-template.php
    $menu = wp_nav_menu($options);

    if ($options['echo']) {
        echo $menu;
    } else {
        return $menu;
    }
} // }}}

/**
 * Filter content as the_content() function would do.
 *
 * @param  string $content
 * @return string
 */
function themifier_filter_content($content) // {{{
{
    $content = apply_filters('the_content', $content);
    $content = str_replace(']]>', ']]&gt;', $content);
    $content = trim($content);
    return $content;
} // }}}

/**
 * @param  int|WP_Post $post_id OPTIONAL
 * @param  string $property OPTIONAL
 * @return string
 */
function themifier_get_content($post_id = null, $property = null) // {{{
{
    // store last retrieved post's data to avoid unnecessary computations
    // for previously processed post (such as in the loop)
    // to reset this storage pass -1 for post_id
    static $result;

    if ($post_id === -1) {
        $result = null;
        return '';
    }

    if ($property === null) {
        return themifier_filter_content(get_the_content());
    }

    $post = get_post($post_id);

    if (empty($post)) {
        return '';
    }

    if (empty($result) || $result['ID'] !== $post->ID) {
        $extended = get_extended($post->post_content);
        $result = array(
            'ID'       => $post->ID,
            'main'     => themifier_filter_content($extended['main']),
            'extended' => themifier_filter_content($extended['extended']),
            'more'     => $extended['more'], // TODO should this be filtered?
        );
    }

    return isset($result[$property]) ? $result[$property] : '';
} // }}}

/**
 * For arguments description see {@see wp_list_categories()}.
 *
 * Additional argument is supported if no walker is passed. count_wrap formats
 * item count in category.
 *
 * @param  array|string $args
 * @return string
 */
function themifier_list_categories($args = null) // {{{
{
    $defaults = array(
        'item_format' => null,
    );
    $args = wp_parse_args($args, $defaults);

    if (empty($args['walker'])) {
        require_once dirname(__FILE__) . '/walker-category.php';
        $args['walker'] = new themifier_walker_category();
    }

    return wp_list_categories($args);
} // }}}

/**
 * @param int $term_id
 * @return array
 */
function themifier_get_category_parents($term_id, array &$visited = array()) // {{{
{
    $term_id = intval($term_id);

    if (!isset($visited[$term_id])) {
        $parent = get_term($term_id, 'category');
        $visited[$term_id] = $parent && !is_wp_error($parent) ? $parent : false;
    } else {
        $parent = $visited[$term_id];
    }

    if ($parent) {
        if ($parent->parent) {
            $parents = themifier_get_category_parents($parent->parent, $visited);
        } else {
            $parents = array();
        }
        return array_merge(array($parent), $parents);
    }

    return array();
} // }}}

/**
 * @return array
 */
function themifier_get_breadcrumbs() // {{{
{
    if (is_home()) {
        return array();
    }

    $breadcrumbs = array(
        array(
            'label' => __('Home'),
            'url'   => themifier_home_url(),
        ),
    );

    switch (true) {
        case is_category():
            $obj = get_queried_object(); // category
            if ($obj && isset($obj->term_id)) {
                $parents = array();
                foreach (themifier_get_category_parents($obj->term_id) as $parent) {
                    array_unshift($parents, array(
                        'label' => $parent->name,
                        'url'   => get_category_link($parent->term_id),
                    ));
                }
                $breadcrumbs = array_merge($breadcrumbs, $parents);
            }
            break;

        case is_page():
            $breadcrumbs[] = array(
                'label' => the_title('', '', false),
                'url'   => get_permalink(),
            );
            break;

        case is_tag():
            $breadcrumbs[] = array(
                'label' => single_tag_title('', false),
                'url'   => get_tag_link(get_queried_object_id()),
            );
            break;

        case is_day():
        case is_month():
        case is_year():
        case is_single():
            $year = get_the_time('Y');
            $month = get_the_time('m');
            $day = get_the_time('j');

            $breadcrumbs[] = array(
                'label' => $year,
                'url'   => get_year_link($year),
            );

            if (is_month() || is_day() || is_single()) {
                $breadcrumbs[] = array(
                    'label' => get_the_time('F'),
                    'url'   => get_month_link($year, $month),
                );
            }
            if (is_day() || is_single()) {
                $breadcrumbs[] = array(
                    'label' => $day,
                    'url'   => get_day_link($year, $month, $day),
                );
            }
            if (is_single()) {
                $breadcrumbs[] = array(
                    'label' => get_the_title(),
                    'url'   => get_permalink(),
                );
            }
            break;

        case is_author():
            $breadcrumbs[] = array(
                'label' => get_the_author(),
                'url'   => get_the_author_meta('url'),
            );
            break;

        case is_search():
            $breadcrumbs[] = array(
                'label' => _x('Search', 'Search widget'),
                'url'   => themifier_home_url() . '?s=' . urlencode($_GET['s']),
            );
            break;

        case is_404():
            $breadcrumbs[] = array(
                'label' => __('Page not found'),
                'url'   => null,
            );
            break;
    }

    if (get_query_var('page') > 1) {
        $breadcrumbs[] = array(
            'label' => sprintf(__('Page %s'), (int) get_query_var('page')),
            'url'   => null,
        );
    }

    return $breadcrumbs;
} // }}}

// if this file is the WP execution context register plugin hooks
if (defined('ABSPATH')) {
    add_action('wp_head', 'themifier_check_language');
    add_filter('logout_url', 'themifier_logout_url', 10, 1);
}
